package com.example.ui

enum class AppLanguage {
    ENGLISH,
    HINDI,
    HINGLISH
}

object Translations {
    fun get(key: String, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.ENGLISH -> when (key) {
                "app_title" -> "Kharcha Tracker"
                "balance_left" -> "Balance Left"
                "monthly_capital" -> "Monthly Capital"
                "today_spent" -> "Today's Spent"
                "month_spent" -> "Monthly Spent"
                "budget_limit" -> "Current Limit"
                "limit_warning" -> "Warning: Limit Exceeded! ⚠️"
                "limit_ok" -> "Within safe budget limits ✅"
                "add_expense" -> "Add Expense"
                "amount_daalo" -> "Enter Amount (₹)"
                "notes_daalo" -> "Enter description / notes"
                "save_expense" -> "Save Expense"
                "recent_expenses" -> "Recent Expenses"
                "no_expenses_yet" -> "No expenses logged yet! 🌸"
                "delete" -> "Delete"
                "profile" -> "Profile Setup"
                "save_profile" -> "Save Profile Info"
                "user_info" -> "User Profile Data"
                "name" -> "Name"
                "role" -> "Your Status"
                "personal" -> "Personal Use 👤"
                "student" -> "Student 🎓"
                "housewife" -> "Housewife 🏡"
                "salaried" -> "Salaried 💼"
                "freelancer" -> "Freelancer 💻"
                "business" -> "Business Owner 🏬"
                "language_label" -> "App Language"
                "mode_label" -> "Theme Mode"
                "light_mode" -> "Light Mode"
                "dark_mode" -> "Dark Mode"
                "food" -> "Food 🍛"
                "travel" -> "Travel 🚗"
                "study" -> "Study 📚"
                "recharge" -> "Recharge 📱"
                "other" -> "Other coin"
                "enter_amount_error" -> "Please enter a valid amount!"
                "capital_helper" -> "Put allowance / capital received at month start"
                "limit_type" -> "Reset limit choice"
                "daily_reset" -> "Daily reset"
                "monthly_reset" -> "Monthly reset"
                "set_capital" -> "Set Monthly Capital (₹)"
                "set_limit" -> "Set Budget Limit (₹)"
                "select_date" -> "Select Date"
                "today" -> "Today"
                "yesterday" -> "Yesterday"
                "date" -> "Expense Date"
                "days_left" -> "days left in month"
                "suggested_limit" -> "Daily suggestion based on budget limit: "
                "rupee_symbol" -> "₹"
                else -> key
            }
            AppLanguage.HINDI -> when (key) {
                "app_title" -> "खर्चा ट्रैकर"
                "balance_left" -> "बचा हुआ बैलेंस"
                "monthly_capital" -> "महीने का बजट"
                "today_spent" -> "आज का खर्चा"
                "month_spent" -> "इस महीने का खर्च"
                "budget_limit" -> "बजट लिमिट"
                "limit_warning" -> "चेतावनी: लिमिट से ज्यादा! ⚠️"
                "limit_ok" -> "बजट लिमिट के अंदर सुरक्षित ✅"
                "add_expense" -> "खर्चा जोड़ें"
                "amount_daalo" -> "रकम डालें (₹)"
                "notes_daalo" -> "खर्चे की जानकारी / विवरण"
                "save_expense" -> "खर्चा सहेजें"
                "recent_expenses" -> "हाल के खर्चे"
                "no_expenses_yet" -> "अभी तक कोई खर्चा नहीं है! 🌸"
                "delete" -> "हटाएं"
                "profile" -> "प्रोफ़ाइल सेटिंग"
                "save_profile" -> "प्रोफ़ाइल सुरक्षित करें"
                "user_info" -> "उपयोगकर्ता जानकारी"
                "name" -> "नाम"
                "role" -> "श्रेणी / पेशा"
                "personal" -> "सामान्य यूज़र 👤"
                "student" -> "छात्र 🎓"
                "housewife" -> "ग़ृहणी 🏡"
                "salaried" -> "नौकरीपेशा 💼"
                "freelancer" -> "फ्रीलांसर 💻"
                "business" -> "व्यापारी 🏬"
                "language_label" -> "ऐप की भाषा"
                "mode_label" -> "थीम मोड"
                "light_mode" -> "लाइट थीम"
                "dark_mode" -> "डार्क थीम"
                "food" -> "भोजन 🍛"
                "travel" -> "यात्रा 🚗"
                "study" -> "पढ़ाई 📚"
                "recharge" -> "रिचार्ज 📱"
                "other" -> "अन्य coin"
                "enter_amount_error" -> "कृपया सही रकम डालें!"
                "capital_helper" -> "महीने की शुरुआत में मिला कुल खर्च/बजट"
                "limit_type" -> "लिमिट रीसेट का तरीका"
                "daily_reset" -> "दैनिक बजट"
                "monthly_reset" -> "मासिक बजट"
                "set_capital" -> "महीने का कुल बजट सेट करें (₹)"
                "set_limit" -> "बजट लिमिट सेट करें (₹)"
                "select_date" -> "तारीख चुनें"
                "today" -> "आज"
                "yesterday" -> "कल"
                "date" -> "खर्चे की तारीख"
                "days_left" -> "महीने के दिन बचे"
                "suggested_limit" -> "बजट लिमिट के आधार पर आज की सलाह: "
                "rupee_symbol" -> "₹"
                else -> key
            }
            AppLanguage.HINGLISH -> when (key) {
                "app_title" -> "Kharcha Tracker"
                "balance_left" -> "Balance Bachaa"
                "monthly_capital" -> "Monthly Capital"
                "today_spent" -> "Aaj ka kharcha"
                "month_spent" -> "Month ka kharcha"
                "budget_limit" -> "Budget Limit"
                "limit_warning" -> "Arey! Limit se bahar ho gaye ⚠️"
                "limit_ok" -> "Sab control me hai, limit ke andar ✅"
                "add_expense" -> "Add Expense"
                "amount_daalo" -> "Amount daalo (₹)"
                "notes_daalo" -> "Kaha kharch kiya? (Optional)"
                "save_expense" -> "Save expense"
                "recent_expenses" -> "Haal ka kharcha"
                "no_expenses_yet" -> "Abhi tak koi kharcha nahi likha! 🌸"
                "delete" -> "Delete karein"
                "profile" -> "Profile Details"
                "save_profile" -> "Save profile details"
                "user_info" -> "Apni Detail Likhein"
                "name" -> "Naam"
                "role" -> "Aap kya karte hain?"
                "personal" -> "Personal Use 👤"
                "student" -> "Student 🎓"
                "housewife" -> "Housewife 🏡"
                "salaried" -> "Salaried Job 💼"
                "freelancer" -> "Freelancer 💻"
                "business" -> "Business Owner 🏬"
                "language_label" -> "App ki Bhasha"
                "mode_label" -> "Screen Style"
                "light_mode" -> "Light mode"
                "dark_mode" -> "Dark mode"
                "food" -> "Khana 🍛"
                "travel" -> "Safar 🚗"
                "study" -> "Padhai 📚"
                "recharge" -> "Recharge 📱"
                "other" -> "Kuch aur coin"
                "enter_amount_error" -> "Sahi amount daalo!"
                "capital_helper" -> "Month ke shuruat me mila budget"
                "limit_type" -> "Limit reset option"
                "daily_reset" -> "Daily reset"
                "monthly_reset" -> "Monthly reset"
                "set_capital" -> "Start of Month Capital daalo (₹)"
                "set_limit" -> "Kharch karne ki Limit daalo (₹)"
                "select_date" -> "Date select karo"
                "today" -> "Aaj"
                "yesterday" -> "Kal"
                "date" -> "Kharch ki Date"
                "days_left" -> "din bache hain"
                "suggested_limit" -> "Budget limit ke hisab se roj ka kharcha: "
                "rupee_symbol" -> "₹"
                else -> key
            }
        }
    }
}
